import "./globals.css";
import type { Metadata } from "next";
import { pokeFont } from "./styles/fonts";

export const metadata: Metadata = {
  title: "Pokédex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="leading-4 box-border">
      <body className={`${pokeFont.className} bg-black`}>{children}</body>
    </html>
  );
}
